# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/Azure/azure-k8s-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |  
          echo 'export VERSION="$(shell git describe --tags --abbrev=0 --exact-match 2>/dev/null || echo beta).$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - run: |
          make build
      - run:
          name: Save Docker image layer cache
          command: |
            make save
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - app.tar
  build_pr:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/Azure/azure-k8s-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          make build
  deploy:
    docker:
      - image: circleci/golang:1.10.3
    steps:
      - setup_remote_docker
      - run: |  
          echo 'export VERSION="$(shell git describe --tags --abbrev=0 --exact-match 2>/dev/null || echo beta).$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Push it 
          command: |
            docker load < app.tar
            make push
      
workflows:
  version: 2
  build_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build_pr:
    jobs:
      - build_pr:
          filters:
            branches:
              ignore: master
