# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/Azure/azure-k8s-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |  
          echo 'export VERSION="$CIRCLE_WORKFLOW_ID"' >> $BASH_ENV
          echo 'export REGISTRY_PATH="public/k8s/metrics"' >> $BASH_ENV
      - run: 
          name: install helm
          command: .circleci/install-helm.sh
            
      - run: make build
      - run:
          name: Save Docker image layer cache
          command: make save
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - app.tar
  build_pr:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/Azure/azure-k8s-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: install helm
          command: .circleci/install-helm.sh
      - run: make build
  deploy:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/Azure/azure-k8s-metrics-adapter
    steps:
      - checkout
      - setup_remote_docker
      - run: |  
          echo 'export VERSION="$(if [ -z ${CIRCLE_TAG} ]; then echo "beta"; else echo "$CIRCLE_TAG"; fi)-$CIRCLE_BUILD_NUM"' >> $BASH_ENV
          echo 'export IMAGE="public/k8s/metrics/adapter"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run: docker load < app.tar
      - run: make tag-ci
      - run: make push
workflows:
  version: 2
  build_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build_pr:
    jobs:
      - build_pr:
          filters:
            branches:
              ignore: master
