{{- if .Values.azureAuthentication.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "azure-k8s-metrics-adapter.name" . }}
    chart: {{ template "azure-k8s-metrics-adapter.chart" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "azure-k8s-metrics-adapter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if and (not (eq "msi" .Values.azureAuthentication.method)) (not (eq "aadPodIdentity" .Values.azureAuthentication.method)) }}
  azure-tenant-id: {{ .Values.azureAuthentication.tenantID | b64enc | quote }}
  azure-client-id: {{ .Values.azureAuthentication.clientID | b64enc | quote }}
  {{- end }}
  {{- if eq "clientSecret" .Values.azureAuthentication.method }}
  azure-client-secret: {{ .Values.azureAuthentication.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if eq "clientCertificate" .Values.azureAuthentication.method }}
  azure-client-certificate: {{ .Values.azureAuthentication.clientCertificate | b64enc | quote }}
  azure-client-certificate-password: {{ .Values.azureAuthentication.clientCertificatePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.defaultSubscriptionId }}
  azure-subscription-id: {{ .Values.defaultSubscriptionId | b64enc | quote }}
  {{- end }}
  {{- if .Values.applicationInsightsAppID }}
  app-insights-app-id: {{ .Values.applicationInsightsAppID | b64enc | quote }}
  {{- end }}
  {{- if .Values.applicationInsightsAPIKey }}
  app-insights-key: {{ .Values.applicationInsightsAPIKey | b64enc | quote }}
  {{- end }}
{{- end }}